server:
  port: 8080

spring:
  profiles:
    active: mysql  # Change this to 'mysql' or 'h2' as needed
  application:
    name: institution-management
    
jwt:
  secret: SMG12345
  expiration: 18000000 # 5 hours in milliseconds